name: Deploy Tusha Chat

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Secrets
        run: |
          sed -i 's|%%BOT_TOKEN%%|${{ secrets.TELEGRAM_BOT_TOKEN }}|g' index.html
          sed -i 's|%%API_ID%%|${{ secrets.TELEGRAM_API_ID }}|g' index.html
          sed -i 's|%%API_HASH%%|${{ secrets.TELEGRAM_API_HASH }}|g' index.html
          sed -i 's|%%WEBHOOK%%|${{ secrets.DISCORD_WEBHOOK_URL }}|g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          force_orphan: true
